# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
# The first ten terms would be:
#                       
#                       1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...


# def list_tri_num(limit):
#   triangular_numbers = [] #initialize empty list 
#   triangular_numbers_factors = []
#   counter = 0 # to add numbers
#   i,j = 0,0
#     global i,j, triangular_numbers,counter 
#     while i <= limit:
#         while j <= i:
#             counter += j
#             j += 1
#         triangular_numbers.append(counter)
#         i += 1
#     return triangular_numbers

import math 

def get_factors(n):
    number_of_factors = 0
    for i in range(1, int(math.ceil(math.sqrt(n)))):
        if n % i == 0:
            number_of_factors +=2
        else:
            continue
    return number_of_factors

x=1
for y in range(2,1000000):
    x += y
    if get_factors(x) >= 500:
        print(x)
        break

